    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: grader
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
